//! Cross-session approval runtime.
//!
//! Mirrors kimi-cli's `ApprovalRuntime`: a single coordinator that collects
//! approval requests from any `SessionActor` (root, foreground subagent, or
//! background subagent), forwards them to the UI, and routes user responses
//! back to the waiting actor.

use std::collections::HashMap;
use std::sync::Mutex;
use std::sync::atomic::{AtomicU64, Ordering};

use tokio::sync::{mpsc, oneshot};

/// Result returned to a waiting actor when the user resolves a request.
#[derive(Debug, Clone, Copy)]
pub struct ApprovalResult {
  /// Whether the tool was approved.
  pub approved: bool,
  /// Whether all remaining tools in the batch should be rejected.
  pub reject_remaining: bool,
}

/// An approval request forwarded to the UI.
#[derive(Debug, Clone)]
pub struct ApprovalRequest {
  /// Stable approval request id generated by the runtime.
  pub approval_id: String,
  /// Session or agent that initiated the request.
  pub source_id: String,
  /// Optional source kind, e.g. "background_agent".
  pub source_kind: Option<String>,
  /// Tool call id that needs approval.
  pub tool_call_id: String,
  /// Tool name.
  pub name: String,
  /// Optional diff preview for file-modifying tools.
  pub diff_preview: Option<String>,
  /// Position of this tool in the overall execution list (1-based).
  pub position: usize,
  /// Total number of tools in the current execution batch.
  pub total: usize,
}

/// Internal state for a pending approval request.
struct PendingRequest {
  source_id: String,
  source_kind: Option<String>,
  responder: oneshot::Sender<ApprovalResult>,
}

impl std::fmt::Debug for PendingRequest {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    f.debug_struct("PendingRequest")
      .field("source_id", &self.source_id)
      .field("source_kind", &self.source_kind)
      .field("responder", &"<oneshot sender>")
      .finish()
  }
}

/// Coordinator for interactive tool approvals across multiple sessions.
#[derive(Debug)]
pub struct ApprovalRuntime {
  next_id: AtomicU64,
  pending: Mutex<HashMap<String, PendingRequest>>,
  ui_tx: Mutex<Option<mpsc::UnboundedSender<ApprovalRequest>>>,
}

impl ApprovalRuntime {
  /// Create a new empty approval runtime.
  pub fn new() -> Self {
    Self {
      next_id: AtomicU64::new(1),
      pending: Mutex::new(HashMap::new()),
      ui_tx: Mutex::new(None),
    }
  }

  /// Bind a UI channel that receives approval requests.
  pub fn bind_ui(&self, ui_tx: mpsc::UnboundedSender<ApprovalRequest>) {
    *self.ui_tx.lock().unwrap() = Some(ui_tx);
  }

  /// Generate a fresh approval id.
  fn fresh_id(&self) -> String {
    let n = self.next_id.fetch_add(1, Ordering::Relaxed);
    format!("apr-{}", n)
  }

  /// Submit an approval request and return a receiver that resolves when the
  /// user responds.
  ///
  /// The receiver resolves to `Err` if the runtime is dropped while the request
  /// is pending.
  #[allow(clippy::too_many_arguments)]
  pub fn submit_request(
    &self,
    source_id: String,
    source_kind: Option<String>,
    tool_call_id: String,
    name: String,
    diff_preview: Option<String>,
    position: usize,
    total: usize,
  ) -> (String, oneshot::Receiver<ApprovalResult>) {
    let approval_id = self.fresh_id();
    let (tx, rx) = oneshot::channel();

    self.pending.lock().unwrap().insert(
      approval_id.clone(),
      PendingRequest {
        source_id: source_id.clone(),
        source_kind: source_kind.clone(),
        responder: tx,
      },
    );

    let request = ApprovalRequest {
      approval_id: approval_id.clone(),
      source_id,
      source_kind,
      tool_call_id,
      name,
      diff_preview,
      position,
      total,
    };

    if let Some(ui_tx) = self.ui_tx.lock().unwrap().as_ref() {
      let _ = ui_tx.send(request);
    }

    (approval_id, rx)
  }

  /// Convenience helper that submits a request and awaits the response.
  #[allow(clippy::too_many_arguments)]
  #[allow(dead_code)]
  pub async fn request_approval(
    &self,
    source_id: String,
    source_kind: Option<String>,
    tool_call_id: String,
    name: String,
    diff_preview: Option<String>,
    position: usize,
    total: usize,
  ) -> ApprovalResult {
    let (_id, rx) = self.submit_request(
      source_id,
      source_kind,
      tool_call_id,
      name,
      diff_preview,
      position,
      total,
    );
    match rx.await {
      Ok(result) => result,
      Err(_) => ApprovalResult {
        approved: false,
        reject_remaining: false,
      },
    }
  }

  /// Respond to a pending approval request.
  ///
  /// Returns true if the request existed and was resolved.
  pub fn respond(&self, approval_id: &str, approved: bool, reject_remaining: bool) -> bool {
    let pending = self.pending.lock().unwrap().remove(approval_id);
    match pending {
      Some(req) => {
        let _ = req.responder.send(ApprovalResult {
          approved,
          reject_remaining,
        });
        true
      }
      None => false,
    }
  }
}

impl Default for ApprovalRuntime {
  fn default() -> Self {
    Self::new()
  }
}

#[cfg(test)]
mod tests {
  use std::sync::Arc;

  use super::*;

  #[tokio::test]
  async fn test_request_and_respond() {
    let runtime = Arc::new(ApprovalRuntime::new());
    let (ui_tx, mut ui_rx) = mpsc::unbounded_channel();
    runtime.bind_ui(ui_tx);

    let runtime2 = runtime.clone();
    let handle = tokio::spawn(async move {
      runtime2
        .request_approval(
          "session-1".to_string(),
          None,
          "call-1".to_string(),
          "WriteFile".to_string(),
          None,
          1,
          1,
        )
        .await
    });

    let request = ui_rx.recv().await.unwrap();
    assert!(runtime.respond(&request.approval_id, true, false));

    let result = handle.await.unwrap();
    assert!(result.approved);
    assert!(!result.reject_remaining);
  }
}
